/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAvatar: typeof import('nuxt-ui-vue')['UAvatar']
    UBreadcrumb: typeof import('nuxt-ui-vue')['UBreadcrumb']
    UButton: typeof import('nuxt-ui-vue')['UButton']
    UDivider: typeof import('nuxt-ui-vue')['UDivider']
    UIcon: typeof import('nuxt-ui-vue')['UIcon']
    UInputMenu: typeof import('nuxt-ui-vue')['UInputMenu']
    UModal: typeof import('nuxt-ui-vue')['UModal']
    UNotifications: typeof import('nuxt-ui-vue')['UNotifications']
    UPagination: typeof import('nuxt-ui-vue')['UPagination']
    USelectMenu: typeof import('nuxt-ui-vue')['USelectMenu']
    USkeleton: typeof import('nuxt-ui-vue')['USkeleton']
    USlideover: typeof import('nuxt-ui-vue')['USlideover']
    UTable: typeof import('nuxt-ui-vue')['UTable']
    UTabs: typeof import('nuxt-ui-vue')['UTabs']
    UToggle: typeof import('nuxt-ui-vue')['UToggle']
  }
}
